Insert into DEPT (DEPTNO,DNAME,LOC) values (10,'ACCOUNTINGX','NEW YORK');
Insert into DEPT (DEPTNO,DNAME,LOC) values (20,'RESEARCHX','DALLAS');
Insert into DEPT (DEPTNO,DNAME,LOC) values (30,'SALESX','CHICAGO');
Insert into DEPT (DEPTNO,DNAME,LOC) values (40,'OPERATIONSX','BOSTON');