CREATE TABLE DEPT (
	DEPTNO INTEGER, 
	DNAME VARCHAR(30), 
	LOC VARCHAR(30), 
	PRIMARY KEY (DEPTNO)
);
INSERT INTO
    DEPT (DEPTNO,DNAME,LOC)
VALUES
    (10,'ACCOUNTING_H2','NEW YORK'),
    (20,'RESEARCH_H2','DALLAS'),
    (30,'SALES_H2','CHICAGO'),
    (40,'OPERATIONS_H2','BOSTON');