CREATE TABLE DEPT (
	DEPTNO INTEGER auto_increment,
	DNAME VARCHAR(30), 
	LOC VARCHAR(30), 
	PRIMARY KEY (DEPTNO)
);
INSERT INTO
    DEPT (DEPTNO,DNAME,LOC)
VALUES
    (10,'ACCOUNTING','NEW YORK'),
    (20,'RESEARCH','DALLAS'),
    (30,'SALES','CHICAGO'),
    (40,'OPERATIONS','BOSTON');