CREATE DATABASE IF NOT EXISTS EMP_DEPT DEFAULT CHARACTER SET utf8;
USE EMP_DEPT;
DROP TABLE if exists DEPT;

CREATE TABLE DEPT (	
	DEPTNO INTEGER, 
	DNAME VARCHAR(30), 
	LOC VARCHAR(30), 
	PRIMARY KEY (DEPTNO)
);