CREATE TABLE DEPT (
	DEPTNO INTEGER, 
	DNAME VARCHAR(30), 
	LOC VARCHAR(30), 
	PRIMARY KEY (DEPTNO)
);
INSERT INTO
    DEPT (DEPTNO,DNAME,LOC)
VALUES
    (10,'ACCOUNTINGNY','NEW YORK'),
    (20,'RESEARCH','DALLAS'),
    (30,'SALES','CHICAGO'),
    (40,'OPERATIONS','BOSTON');